hash-format = "sha256"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "8ef7235675c71f938772fe5683b1b56cd952d3865a66cfd02dc8f3707d7f72b3"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "17e7de63579b066cea4b6db60318617956c1925891edc562085cd72544a763b9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "af8dc072b8d618de96260fccfa5fab7f79c5ca9679bc3a57473f6df4ce218fff"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7a2991786a3523846ee1dcaa4c34c9f1d7a544ea4dbf252df8482b19549009b4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6d88f4cdcc5c08a06c25b83f67bd0e0896d61489ca6b5e508a30a10a00caa7f6"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6085d2f0a5deabc026667492ac344d9b9007c80ccadb3f916fe9b0ec3037f022"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7adc0d54f139075d8f90dae18ca476753cc3145a70e09c9327736024adfe9b30"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "db1b2a280e596ea170ab575abc74ac9da9afdd9d4f8108e330cdcb034f8e4c55"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "b5a01826b0ec0ea8c8e1fe0eab064729c0b532b738788cc93eed03ca5c897cb6"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "6f8f908c216a72efc2aab289578eeb4399a259eae29fbac8bcc88df840e3c0bf"
metafile = true

[[files]]
file = "mods/gputape.pw.toml"
hash = "87a0a56a4cdc0c3a4bffc41f1902c99eefc3aa5f9504005bfda5a1ffcbb1b50e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "402069ebe33a1f19e6e5c0c0235267b832ba44617f15ddbdc677faf2a2607e38"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "b89656eaf7e4404d8d2c5b1e1155aae85a839939f83cab6d1b5e791412ad5f86"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c66e4b3576440113259b5bae8d0660b8e0023ce852156f27383f8651ecc4bfe3"
metafile = true

[[files]]
file = "mods/moonrise-opt.pw.toml"
hash = "c40a3498aa0c1bdb091b327b414c4adabe8618f1fc9a75614800c9fefef12977"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0544fefc6f04f2b408b2c6b4dd3e4bf7d0a4048f1fad6ddf63357549d7446165"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "54dd8b88e92786d96c2487b7d6a473fbb7cd4576cec3a543788cfab327ffd623"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "08b89b53c392b5fa29198418df8598404d93c58eae40d432caed797c828adbd5"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3cbdb02ff4be022d7e0f9b82cd64a36669d5986d7ed3ddcf7bcdbacc0b1b4b2a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "383d8df46529ce54b4b0574be2fd9eba4f45d8c85aa668604e152fca3e439f5a"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "50855fdced2ad535c842825b761e62b339168b9ea158e452bdd4f6467a102645"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4e4627ce19e119721a27a2ef00769d3a744f36db67d11ad3959d785462aefe1f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "b97b297fab12e137c58874ae776402cfa29374c8ff50c9f18ef27442b65336e6"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "022c64cbff3fbce3b4a988405c6cb492a46592c83e842752331844de68c1d8c0"
metafile = true
