hash-format = "sha256"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "ae86765993c59b09e06f972045b8f780e06c504f5210c0991a3b27b95dfacc80"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "8ef7235675c71f938772fe5683b1b56cd952d3865a66cfd02dc8f3707d7f72b3"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "fe9c77327c94f4a60632f3a56a7a9496f9f2f00e12ab42541eb433266a423b16"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ab92afc9c86b581a10eb4e8dc52a3640deeb6d03fb662f6f53b2a21e87d74405"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "d541d1522108112346d35a6e9a3a9979d735cfc766d3ea6477c6306450c35f23"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d980c9bbc31a2fbac6070ed2c8992e2f1527839c54c4299d7a52f015775d8067"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "9a816f2d1841566fa111d67830df9e429df90c1e77eac417f01aea1a9047def8"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f1d73d7f9dfe612183c92044578ec1a0a6823f4e940562992c0a103ba881f344"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "098d6976a738658ca490cc58e9fab19f06cd1a7b23199b6f1ee108d866333e22"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "f3c666b7a4140f9944920c8279ba897feb3e7ec48086d9b10862ea9b012aeacb"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "ef9af7af5823c98a39c6fd64c70d47cde41a14a3093baae5de888d5962deae3c"
metafile = true

[[files]]
file = "mods/gputape.pw.toml"
hash = "1679bf969162c01ae8f2e3e479f3179075c1430491f05c58f71a51d7e9675a07"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5f40e2db6037f733566c81e8f11ca3c425d738eb5a182658691f36d041b5df40"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "03436f3158e885ebe51f15a98e0afe611bd3391ad21f92b8ac7a185afb9d36c9"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "b89656eaf7e4404d8d2c5b1e1155aae85a839939f83cab6d1b5e791412ad5f86"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/moonrise-opt.pw.toml"
hash = "47bdd55765d74cc1e458cc6760a78748d637169b507051aa46065db6c9c73786"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "204a4b3b041fad4bb4dc543c74d540fcf239710494d2130cebe700bf1d8a7805"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "54dd8b88e92786d96c2487b7d6a473fbb7cd4576cec3a543788cfab327ffd623"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "4bf3b4e6ce176f34d70fa961fee580956567b0a79e25e3be58e020b7e9f42e32"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "978c05608ae60f7e40925d145910c124bb90db5db0ea8f8786fccd677eced4d6"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1600b1e64b297d68bafb4f5e5eeef08117645ac24922696da10c711ae587c06b"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "50855fdced2ad535c842825b761e62b339168b9ea158e452bdd4f6467a102645"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4f57108f9e1c6281cfdaf3812e6bc2a2f16609a845c9912218ada90b1603e1b3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "88e1cf290eb023af36efe7b20d1fb880597326d132189763b293a644c203ebfb"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "b97b297fab12e137c58874ae776402cfa29374c8ff50c9f18ef27442b65336e6"
metafile = true

[[files]]
file = "mods/super-fast-math.pw.toml"
hash = "8c64c3ab733f1bcc4d614ea5f0912b85307295299c57f0d0d46d7f1a171a815c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f82809b1d8eaab731b217b01589ab13e1374c4d422f18640ba3262b55f3b4cfa"
metafile = true
