name = "Kami Chan Optimized"
author = "mja00"
version = "19.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a87b8bb36f81eddf375012e05404ac8065bc6209136acdb0bda7e063b4b8627d"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = [
    "1.21.10",
]
