name = "Kami Chan Optimized"
author = "mja00"
version = "18.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e683fc7060453254c7b17a1d76fd2c6a91331755905c9787f2546a5e83ae3b19"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = [
    "1.21.9",
]
