name = "Kami Chan Optimized"
author = "mja00"
version = "19.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2102f27c640c135827e41dc35731d4dbf1118c75beace1a01486477e56d0fbc"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = [
    "1.21.10",
]
