name = "Kami Chan Optimized"
author = "mja00"
version = "19.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5afeac271370eb8aac55f3399174e99a3e4be6061c8c92ce2777ad30e1e6245c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = [
    "1.21.10",
]
