name = "Paper Chan Optimized"
author = "mja00"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b81c9e9d9e6e21a9865a2dded0dfd77e7683d679b98fe5b0114eaed9a31f17e"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
