name = "Kami Chan Optimized"
author = "mja00"
version = "19.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9ef13b2bbd85520a88511815d5b5311eaa6f92d2a63d07206311f1722cb8f87"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = [
    "1.21.10",
]
