name = "Kami Chan Optimized"
author = "mja00"
version = "19.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cc60fcd94a68d518d59d3db6b8ae1dec75b2bb32414d03993c9500aabd51da0"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = [
    "1.21.10",
]
