name = "Kami Chan Optimized"
author = "mja00"
version = "18.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c3dcdd9e1e599d66c2025f9e227e2b284035805c5c0157d405f62a1427dcd01"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = [
    "1.21.9",
]
