name = "Kami Chan Optimized"
author = "mja00"
version = "19.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "388e7841b524b121deccfc03386d0e57207202f00ac4c6c37186cdcf4c4bb3b4"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = [
    "1.21.10",
]
