name = "Kami Chan Optimized"
author = "mja00"
version = "18.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47a0af9aba4a9ecdd8929446a6be947b5b6c031ec424b0c40f13f3d4b2e9ab77"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = [
    "1.21.9",
]
